"""add completed order status

Revision ID: 55f0dea657b3
Revises: bdd43317142c
Create Date: 2026-08-04 18:24:39.047186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f0dea657b3'
down_revision: Union[str, Sequence[str], None] = 'bdd43317142c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'completed';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
