"""link users and customers

Revision ID: bdd43317142c
Revises: 7928fcc51e4c
Create Date: 2026-08-04 13:12:23.333895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd43317142c'
down_revision: Union[str, Sequence[str], None] = '7928fcc51e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'customers', ['user_id'])
    op.create_foreign_key(None, 'customers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
