"""Update payment constraints

Revision ID: f0675dc01c66
Revises: 4df46f614630
Create Date: 2026-08-01 20:36:44.276535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0675dc01c66'
down_revision: Union[str, Sequence[str], None] = '4df46f614630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_payments_order_id", 'payments', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_payments_order_id", 'payments', type_='unique')
    # ### end Alembic commands ###
